name: web_scaffold
description: Flutter library that helps create webpages faster
version: 0.0.1

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
